# Site settings
title: revolution.ready(riseUp)
email: support@eye4games.com
description: > # this means to ignore newlines until "baseurl:"
  Get ready to rise up.
baseurl: "/rise/" # the subpath of your site, e.g. /blog/
url: "http://eye4games.github.io" # the base hostname & protocol for your site
twitter_username: Eye4Games
github_username:  Eye4Games

# Build settings
markdown: kramdown
